export const registryMetadata = {
  title: "Malaysian Legal Authority Registry",
  jurisdiction: "Malaysia",
  phase: "Source directory and taxonomy foundation",
  sourcePackage: "Malaysian_Legal_Authority_Registry_Starter",
};

const sources = [
  [
    "AGC_LOM",
    "Federal Legislation Portal (Laws of Malaysia)",
    "Official legislation",
    "Free public",
    "https://lom.agc.gov.my/",
    "Official primary",
    "Metadata and deep links",
    "Verify terms first",
    "Federal Constitution; principal and amending Acts; Ordinances; P.U.(A); P.U.(B); repealed, revised and translated laws",
    "Treat the current official text and Gazette status as controlling; preserve source URL and retrieval date.",
  ],
  [
    "JUDICIARY_MAIN",
    "Office of the Chief Registrar, Federal Court of Malaysia",
    "Official judiciary",
    "Free public",
    "https://www.kehakiman.gov.my/",
    "Official primary",
    "Metadata and deep links",
    "Verify terms first",
    "Court hierarchy; judiciary notices; practice information; official service links",
    "Use as the main directory for Malaysian Judiciary resources.",
  ],
  [
    "EJUDGMENT",
    "Malaysia eJudgment",
    "Official case law",
    "Free public",
    "https://ejudgment.kehakiman.gov.my/EJudgmentWeb/SearchPage.aspx",
    "Official primary",
    "Metadata search and deep links",
    "Verify terms first",
    "Published Federal Court, Court of Appeal, High Court and available Sessions Court judgments",
    "Store neutral metadata, court, judge, date, case number, citation, status and source link where available.",
  ],
  [
    "ECOURT",
    "e-Court Services",
    "Official court services",
    "Mixed public / authenticated",
    "https://ecourtservices.kehakiman.gov.my/",
    "Official service",
    "External link only",
    "No",
    "Cause lists; permitted online file search; court service links",
    "Do not ingest confidential, restricted, family, sealed or personal case material.",
  ],
  [
    "CLJ",
    "CLJLaw",
    "Licensed legal research",
    "Paid subscription",
    "https://www.cljlaw.com/",
    "Secondary and reported primary",
    "Licensed connector or external link",
    "No without written licence",
    "Reported and unreported cases; federal and state laws; articles; forms; precedents; practice directions",
    "Do not scrape or republish subscriber content. Store lawful citations, links and user-created notes only.",
  ],
  [
    "LEXIS_MY",
    "Lexis+ Malaysia / LexisNexis Malaysia",
    "Licensed legal research",
    "Paid subscription",
    "https://www.lexisnexis.com/en-my",
    "Secondary and reported primary",
    "Licensed API connector or external link",
    "No without written licence",
    "Malayan Law Journal; case law; legislation; annotations; practical guidance; forms; precedents; analytics",
    "Use only under the applicable subscription, API and content licence.",
  ],
  [
    "LAWNET_MY",
    "LawNet Malaysia",
    "Licensed Gazette and research",
    "Paid subscription",
    "https://www.lawnet.com.my/",
    "Gazette and secondary",
    "Licensed connector or external link",
    "No without written licence",
    "Government Gazettes; General Notices; Acts; Rules; Codes; case-law reports",
    "Use for Gazette tracking; preserve Gazette number, publication date and source.",
  ],
  [
    "MALAYSIAN_BAR",
    "Malaysian Bar",
    "Professional materials",
    "Mixed public / member",
    "https://www.malaysianbar.org.my/",
    "Professional secondary",
    "Metadata and deep links",
    "Verify terms first",
    "Bar Council circulars; practice materials; professional-rules information; library resources",
    "Distinguish binding legislation and rules from guidance, circulars and commentary.",
  ],
  [
    "PARLIAMENT_MY",
    "Parliament of Malaysia",
    "Official legislative materials",
    "Free public",
    "https://www.parlimen.gov.my/",
    "Official legislative history",
    "Metadata and deep links",
    "Verify terms first",
    "Bills; Order Papers; Hansard and debates; committee and parliamentary materials",
    "Use for legislative history; enacted law should link to AGC Laws of Malaysia and the applicable Gazette.",
  ],
  [
    "E_FEDERAL_GAZETTE",
    "Federal Gazette access through official or authorised sources",
    "Official Gazette",
    "Mixed",
    "https://lom.agc.gov.my/",
    "Official primary",
    "Metadata and deep links",
    "Verify terms first",
    "Acts as gazetted; P.U.(A); P.U.(B); commencement and amendment notices",
    "Capture Gazette identifier, publication date, commencement date and relationship to the principal law.",
  ],
];

export const registrySourceRecords = sources.map(
  ([
    id,
    title,
    category,
    access,
    sourceUrl,
    rank,
    integration,
    copying,
    content,
    note,
  ]) => ({
    registryId: id,
    type: "Authority source",
    title,
    jurisdiction: "Malaysia",
    category,
    access,
    sourceUrl,
    citation: id,
    status: access,
    summary: content,
    source: registryMetadata.sourcePackage,
    treatment: `${note} Authority ranking: ${rank}. Integration: ${integration}. Bulk copy: ${copying}.`,
    authorityRank: rank,
    integrationMode: integration,
    licenceClass: copying,
  }),
);

const taxonomy = [
  [
    "Constitution",
    "Federal Constitution, Articles, Schedules, amendments and constitutional doctrines",
  ],
  ["Act", "Federal principal Act"],
  ["Amending Act", "Act amending one or more principal laws"],
  ["Ordinance", "Federal, emergency, Sabah, Sarawak or historical ordinance"],
  ["State enactment", "State legislation"],
  [
    "Subsidiary legislation",
    "Rules, regulations, orders, notifications, declarations and by-laws",
  ],
  ["Gazette", "Federal or State Gazette publication"],
  ["Section", "Section of an Act, Code, Ordinance or Enactment"],
  ["Subsection", "Subsection"],
  ["Paragraph", "Paragraph or subparagraph"],
  ["Schedule", "Schedule, form or appendix"],
  ["Practice direction", "Court or registry practice direction"],
  ["Court rule", "Rules of Court or specialist procedural rules"],
  ["Judgment", "Official judgment or grounds of judgment"],
  ["Reported case", "Case published in a recognised law report"],
  ["Unreported case", "Judgment not assigned a report citation"],
  [
    "Precedential treatment",
    "Followed, applied, distinguished, overruled, reversed, affirmed, doubted or not followed",
  ],
  ["Cause of action", "Civil claim or actionable legal basis"],
  ["Offence", "Criminal or regulatory offence"],
  ["Defence", "Civil, criminal, constitutional or statutory defence"],
  [
    "Remedy",
    "Damages, injunction, declaration, judicial review remedy or other relief",
  ],
  [
    "Procedure",
    "Pleading, filing, service, evidence, hearing, appeal or enforcement procedure",
  ],
  [
    "Evidence rule",
    "Admissibility, relevance, burden, standard, privilege or evidential doctrine",
  ],
  ["Doctrine", "Legal or equitable doctrine"],
  ["Principle", "Legal principle or test"],
  ["Maxim", "Latin or other recognised legal maxim"],
  ["Court form", "Official or recognised litigation form"],
  [
    "Drafting precedent",
    "Licensed or internally authored drafting precedent or template",
  ],
  ["Practice note", "Guidance or commentary, not primary authority"],
  [
    "Legal term",
    "Terminology record, cross-linked but not treated as authority",
  ],
  ["Institution", "Court, tribunal, regulator, ministry or legal body"],
  [
    "Person role",
    "Judge, registrar, prosecutor, advocate, solicitor, witness or other legal role",
  ],
];

export const registryTaxonomyRecords = taxonomy.map(
  ([title, summary], index) => ({
    registryId: `TAX-${String(index + 1).padStart(2, "0")}`,
    type: "Authority taxonomy",
    title,
    jurisdiction: "Malaysia",
    category: "Classification",
    access: "Internal registry definition",
    citation: `MLAI taxonomy ${index + 1}`,
    status: "Registry classification",
    summary,
    source: registryMetadata.sourcePackage,
    treatment:
      "Classification metadata only; it does not by itself establish current legal authority.",
  }),
);

export const registryRecords = [
  ...registrySourceRecords,
  ...registryTaxonomyRecords,
];
