# ============================================================
# PHASE 12.0F - CREATE BACKEND / DATABASE PLANNING PACK
# Project: Litigation 360 LEOS
#
# Purpose:
#   Creates the Phase 12.0F planning pack after Phase 12.0E
#   certified DISCOVERY PASS / PATCH NOT APPROVED.
#
# Safety:
#   - Add-only under LEOS_CONTROL
#   - Does not modify app frontend code
#   - Does not modify app backend code
#   - Does not modify database files
# ============================================================

$ErrorActionPreference = "Stop"

$ProjectRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software"
$ControlRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software_LEOS_CONTROL"
$PhaseRoot = Join-Path $ControlRoot "07_DISCOVERY\PHASE12.0F-MATTER-TYPE-BACKEND-DATABASE-PLANNING"

$Folders = @(
    "00_DOCUMENTATION",
    "01_PROTOCOLS",
    "02_PARAMETERS",
    "03_BLUEPRINTS",
    "04_CHECKLISTS",
    "05_PROMPTS",
    "06_SCRIPTS",
    "07_REPORTS",
    "08_EVIDENCE",
    "09_READONLY_SNAPSHOTS",
    "10_LIVE_MONITORING",
    "99_LOGS"
)

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "PHASE 12.0F - CREATE BACKEND / DATABASE PLANNING PACK" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

foreach ($folder in $Folders) {
    New-Item -ItemType Directory -Force -Path (Join-Path $PhaseRoot $folder) | Out-Null
}

function Write-Lines {
    param(
        [string]$Path,
        [string[]]$Lines
    )

    $parent = Split-Path $Path -Parent
    if (-not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }

    Set-Content -LiteralPath $Path -Value ($Lines -join [Environment]::NewLine) -Encoding UTF8
}
$TargetPath = Join-Path $PhaseRoot "00_DOCUMENTATION\PHASE12.0F-EXECUTIVE-DECISION.md"
Write-Lines -Path $TargetPath -Lines @(
    '# PHASE 12.0F EXECUTIVE DECISION'
    ''
    '## Decision'
    ''
    'Matter Type must not be added to the UI yet.'
    ''
    '## Reason'
    ''
    'Phase 12.0E completed successfully as a read-only discovery phase, but the final certification decision was:'
    ''
    'DISCOVERY PASS / PATCH NOT APPROVED.'
    ''
    'The discovery found no confirmed Matter Type support in:'
    ''
    '- Frontend Cases.jsx'
    '- Frontend api.js'
    '- Backend cases.js'
    '- Database schema evidence'
    ''
    'SQLite schema status was also not fully readable because sqlite3 was not available on the machine.'
    ''
    '## Approved Next Course'
    ''
    'Proceed only with read-only backend/database planning.'
    ''
    '## Not Approved'
    ''
    '- Matter Type UI dropdown'
    '- Backend route modification'
    '- Database migration'
    '- API helper patch'
    '- Phase 11 development'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "01_PROTOCOLS\PHASE12.0F-BACKEND-DATABASE-PLANNING-PROTOCOL.md"
Write-Lines -Path $TargetPath -Lines @(
    '# PHASE 12.0F BACKEND / DATABASE PLANNING PROTOCOL'
    ''
    '## Purpose'
    ''
    'This protocol governs the work required before Matter Type can be safely exposed in the Matter Details UI.'
    ''
    '## Golden Rule'
    ''
    'No fake UI fields.'
    ''
    'A field may only appear in the UI when the system can:'
    ''
    '1. Accept it'
    '2. Validate it'
    '3. Store it'
    '4. Return it'
    '5. Display it'
    '6. Edit it'
    '7. Preserve it after reload'
    '8. Roll it back if the patch fails'
    ''
    '## Current Position'
    ''
    'Matter Type is not confirmed in the UI, API, backend, or database.'
    ''
    '## Required Order'
    ''
    '1. Confirm active database file.'
    '2. Confirm active table name.'
    '3. Confirm current columns.'
    '4. Decide whether to add matter_type.'
    '5. Prepare migration plan.'
    '6. Prepare rollback plan.'
    '7. Prepare backend route plan.'
    '8. Prepare API helper plan.'
    '9. Prepare frontend UI plan.'
    '10. Prepare tests.'
    '11. Only then patch.'
    ''
    '## Blocked During This Phase'
    ''
    '- Editing Cases.jsx'
    '- Editing api.js'
    '- Editing cases.js'
    '- Editing database files'
    '- Adding UI dropdowns'
    '- Running migrations'
    '- Phase 11 work'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "02_PARAMETERS\PHASE12.0F-MATTER-TYPE-PARAMETERS.md"
Write-Lines -Path $TargetPath -Lines @(
    '# PHASE 12.0F MATTER TYPE PARAMETERS'
    ''
    '## Proposed Field'
    ''
    'Technical field:'
    ''
    'matter_type'
    ''
    '## Proposed UI Label'
    ''
    'Matter Type'
    ''
    '## Proposed Initial Allowed Values'
    ''
    '- Litigation'
    '- Advisory'
    '- Contract'
    '- Conveyancing'
    '- Debt Recovery'
    '- Employment'
    '- Family'
    '- Criminal'
    '- Corporate'
    '- Other'
    ''
    '## Proposed Default'
    ''
    'Other'
    ''
    '## Storage Rule'
    ''
    'Do not store blank Matter Type if the field becomes mandatory later.'
    ''
    'For first implementation, use either:'
    ''
    '- nullable matter_type with UI fallback to Other'
    '- or non-null matter_type with default Other'
    ''
    'This must be decided after active schema inspection.'
    ''
    '## Backend Validation Rule'
    ''
    'Backend must reject unsupported Matter Type values if validation is added.'
    ''
    '## UI Rule'
    ''
    'The UI must not expose Matter Type until backend/database support exists.'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "03_BLUEPRINTS\PHASE12.0F-BACKEND-DATABASE-BLUEPRINT.md"
Write-Lines -Path $TargetPath -Lines @(
    '# PHASE 12.0F BACKEND / DATABASE BLUEPRINT'
    ''
    '## Target Outcome'
    ''
    'Prepare the system so Matter Type can later be added safely.'
    ''
    '## Required Future Technical Layers'
    ''
    '### 1. Database'
    ''
    'Confirm current active database and table.'
    ''
    'Possible target:'
    ''
    'cases table or matters table'
    ''
    'Possible column:'
    ''
    'matter_type TEXT'
    ''
    '### 2. Backend Route'
    ''
    'Likely file:'
    ''
    'C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software\backend\src\routes\cases.js'
    ''
    'Required future checks:'
    ''
    '- create route accepts matter_type'
    '- update route accepts matter_type'
    '- list route returns matter_type'
    '- detail route returns matter_type if present'
    '- validation handles missing values safely'
    ''
    '### 3. Frontend API'
    ''
    'Likely file:'
    ''
    'C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software\frontend\src\api.js'
    ''
    'Required future checks:'
    ''
    '- create payload sends matter_type'
    '- update payload sends matter_type'
    '- returned response preserves matter_type'
    ''
    '### 4. Frontend UI'
    ''
    'Likely file:'
    ''
    'C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software\frontend\src\pages\Cases.jsx'
    ''
    'Allowed future UI only after backend/database certification:'
    ''
    '- dropdown label: Matter Type'
    '- default value: Other'
    '- list column optional'
    '- detail display optional'
    ''
    '## Implementation Must Be Later'
    ''
    'This blueprint is planning only.'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "04_CHECKLISTS\PHASE12.0F-CHECKS-AND-BALANCES.md"
Write-Lines -Path $TargetPath -Lines @(
    '# PHASE 12.0F CHECKS AND BALANCES'
    ''
    '## Before Any Future Patch'
    ''
    '- [ ] Active database identified'
    '- [ ] Active table identified'
    '- [ ] Current schema exported'
    '- [ ] Existing records counted'
    '- [ ] matter_type absence/presence confirmed'
    '- [ ] migration plan written'
    '- [ ] rollback plan written'
    '- [ ] backend create route mapped'
    '- [ ] backend update route mapped'
    '- [ ] backend list route mapped'
    '- [ ] API helper mapped'
    '- [ ] frontend state mapped'
    '- [ ] browser test plan written'
    '- [ ] npm build check prepared'
    '- [ ] server runtime check prepared'
    '- [ ] live monitor active'
    '- [ ] SSOT update prepared'
    ''
    '## Patch Approval Status'
    ''
    'Matter Type UI patch: NOT APPROVED'
    'Backend patch: NOT APPROVED'
    'Database migration: NOT APPROVED'
    'Phase 11: LOCKED'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "05_PROMPTS\PHASE12.0F-NEXT-THREAD-PROMPT.md"
Write-Lines -Path $TargetPath -Lines @(
    '# PHASE 12.0F NEXT THREAD PROMPT'
    ''
    'Use this prompt in a new thread if needed:'
    ''
    'We are working on Litigation 360 LEOS.'
    ''
    'The current authoritative state is:'
    ''
    '- Phase 12.0D Matter Details UI foundation is substantially complete.'
    '- Phase 12.0E read-only Matter Type discovery completed successfully.'
    '- Phase 12.0E final decision was DISCOVERY PASS / PATCH NOT APPROVED.'
    '- Matter Type was not confirmed in frontend, API, backend, or database evidence.'
    '- SQLite schema inspection could not fully complete because sqlite3 command was unavailable.'
    '- Phase 12.0F is backend/database planning only.'
    '- Do not patch UI, backend, API, or database yet.'
    '- Phase 11 remains locked.'
    ''
    'The next safe action is to identify the active SQLite database and inspect the schema through a safe read-only method before planning any migration or Matter Type field exposure.'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "06_SCRIPTS\Run-PHASE12.0F-ReadOnly-Planning.ps1"
Write-Lines -Path $TargetPath -Lines @(
    '# ============================================================'
    '# PHASE 12.0F - READ-ONLY BACKEND / DATABASE PLANNING'
    '# Purpose:'
    '#   Plan Matter Type backend/database support after Phase 12.0E'
    '#   rejected a Matter Type UI patch.'
    '#'
    '# Safety:'
    '#   - Read-only'
    '#   - Does not modify frontend source code'
    '#   - Does not modify backend source code'
    '#   - Does not modify database files'
    '#   - Creates reports/evidence only'
    '# ============================================================'
    ''
    '$ErrorActionPreference = "Stop"'
    ''
    '$ProjectRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software"'
    '$ControlRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software_LEOS_CONTROL"'
    '$Phase12E = Join-Path $ControlRoot "07_DISCOVERY\PHASE12.0E-MATTER-TYPE-BACKEND-DATA-DISCOVERY"'
    '$PhaseRoot = Join-Path $ControlRoot "07_DISCOVERY\PHASE12.0F-MATTER-TYPE-BACKEND-DATABASE-PLANNING"'
    ''
    '$ReportsRoot = Join-Path $PhaseRoot "07_REPORTS"'
    '$EvidenceRoot = Join-Path $PhaseRoot "08_EVIDENCE"'
    '$SnapshotsRoot = Join-Path $PhaseRoot "09_READONLY_SNAPSHOTS"'
    '$LogsRoot = Join-Path $PhaseRoot "99_LOGS"'
    ''
    '$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"'
    ''
    '$PlanningReportPath = Join-Path $ReportsRoot "PHASE12.0F-READONLY-BACKEND-DATABASE-PLANNING-REPORT-$Timestamp.md"'
    '$PlanningMatrixPath = Join-Path $EvidenceRoot "PHASE12.0F-BACKEND-DATABASE-PLANNING-MATRIX-$Timestamp.csv"'
    '$RouteEvidencePath = Join-Path $EvidenceRoot "PHASE12.0F-BACKEND-ROUTE-EVIDENCE-$Timestamp.csv"'
    '$PackageEvidencePath = Join-Path $EvidenceRoot "PHASE12.0F-PACKAGE-DB-DEPENDENCY-EVIDENCE-$Timestamp.csv"'
    '$DbCandidateReviewPath = Join-Path $EvidenceRoot "PHASE12.0F-SQLITE-CANDIDATE-REVIEW-$Timestamp.csv"'
    '$JsonSummaryPath = Join-Path $EvidenceRoot "PHASE12.0F-PLANNING-SUMMARY-$Timestamp.json"'
    '$LogPath = Join-Path $LogsRoot "PHASE12.0F-READONLY-PLANNING-$Timestamp.log"'
    ''
    'foreach ($dir in @($ReportsRoot, $EvidenceRoot, $SnapshotsRoot, $LogsRoot)) {'
    '    New-Item -ItemType Directory -Force -Path $dir | Out-Null'
    '}'
    ''
    'function Add-Log {'
    '    param([string]$Message)'
    '    $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message'
    '    Add-Content -LiteralPath $LogPath -Value $line -Encoding UTF8'
    '    Write-Host $Message'
    '}'
    ''
    'function Get-RelativePathSafe {'
    '    param([string]$BasePath, [string]$FullPath)'
    '    try {'
    '        $base = [System.IO.Path]::GetFullPath($BasePath).TrimEnd(''\'') + ''\'''
    '        $full = [System.IO.Path]::GetFullPath($FullPath)'
    '        if ($full.StartsWith($base, [System.StringComparison]::OrdinalIgnoreCase)) {'
    '            return $full.Substring($base.Length)'
    '        }'
    '        return $FullPath'
    '    } catch {'
    '        return $FullPath'
    '    }'
    '}'
    ''
    'function Get-FileTextSafe {'
    '    param([string]$Path)'
    '    try {'
    '        if (-not (Test-Path -LiteralPath $Path)) { return "" }'
    '        return Get-Content -LiteralPath $Path -Raw -ErrorAction Stop'
    '    } catch {'
    '        return ""'
    '    }'
    '}'
    ''
    'function Get-FileHashSafe {'
    '    param([string]$Path)'
    '    try {'
    '        if (-not (Test-Path -LiteralPath $Path)) { return "" }'
    '        return (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash'
    '    } catch {'
    '        return "HASH_ERROR"'
    '    }'
    '}'
    ''
    'function Add-MatrixRow {'
    '    param('
    '        [System.Collections.Generic.List[object]]$List,'
    '        [string]$Area,'
    '        [string]$Requirement,'
    '        [string]$CurrentSignal,'
    '        [string]$RequiredFutureAction,'
    '        [string]$RiskIfSkipped,'
    '        [string]$Status'
    '    )'
    ''
    '    $List.Add([pscustomobject]@{'
    '        Area = $Area'
    '        Requirement = $Requirement'
    '        CurrentSignal = $CurrentSignal'
    '        RequiredFutureAction = $RequiredFutureAction'
    '        RiskIfSkipped = $RiskIfSkipped'
    '        Status = $Status'
    '    })'
    '}'
    ''
    'Add-Log "Starting Phase 12.0F read-only backend/database planning."'
    'Add-Log ("ProjectRoot: {0}" -f $ProjectRoot)'
    'Add-Log ("PhaseRoot: {0}" -f $PhaseRoot)'
    ''
    'if (-not (Test-Path -LiteralPath $ProjectRoot)) {'
    '    throw ("Project root not found: {0}" -f $ProjectRoot)'
    '}'
    ''
    '$Latest12ESummary = Get-ChildItem -LiteralPath (Join-Path $Phase12E "08_EVIDENCE") -Filter "PHASE12.0E-DISCOVERY-SUMMARY-*.json" -File -ErrorAction SilentlyContinue |'
    '    Sort-Object LastWriteTime -Descending |'
    '    Select-Object -First 1'
    ''
    '$Latest12EFinalReport = Get-ChildItem -LiteralPath (Join-Path $Phase12E "07_REPORTS") -Filter "PHASE12.0E-FINAL-CERTIFICATION-REPORT-*.md" -File -ErrorAction SilentlyContinue |'
    '    Sort-Object LastWriteTime -Descending |'
    '    Select-Object -First 1'
    ''
    '$Latest12ESqliteCandidates = Get-ChildItem -LiteralPath (Join-Path $Phase12E "08_EVIDENCE") -Filter "PHASE12.0E-SQLITE-CANDIDATES-*.csv" -File -ErrorAction SilentlyContinue |'
    '    Sort-Object LastWriteTime -Descending |'
    '    Select-Object -First 1'
    ''
    '$Summary12E = $null'
    'if ($Latest12ESummary) {'
    '    try {'
    '        $Summary12E = Get-Content -LiteralPath $Latest12ESummary.FullName -Raw | ConvertFrom-Json'
    '    } catch {'
    '        $Summary12E = $null'
    '    }'
    '}'
    ''
    '$CasesJsx = Join-Path $ProjectRoot "frontend\src\pages\Cases.jsx"'
    '$ApiJs = Join-Path $ProjectRoot "frontend\src\api.js"'
    '$BackendCasesRoute = Join-Path $ProjectRoot "backend\src\routes\cases.js"'
    '$BackendPackage = Join-Path $ProjectRoot "backend\package.json"'
    '$FrontendPackage = Join-Path $ProjectRoot "frontend\package.json"'
    ''
    '$casesText = Get-FileTextSafe -Path $CasesJsx'
    '$apiText = Get-FileTextSafe -Path $ApiJs'
    '$routeText = Get-FileTextSafe -Path $BackendCasesRoute'
    '$backendPkgText = Get-FileTextSafe -Path $BackendPackage'
    '$frontendPkgText = Get-FileTextSafe -Path $FrontendPackage'
    ''
    '$terms = @{'
    '    MatterType = @("matter_type", "matterType", "Matter Type", "case_type", "caseType", "Case Type")'
    '    BaseFields = @("title", "client_id", "status", "description")'
    '    SqlInsert = @("INSERT", "insert")'
    '    SqlUpdate = @("UPDATE", "update")'
    '    SqlSelect = @("SELECT", "select")'
    '    SqlCreate = @("CREATE TABLE", "create table")'
    '    RoutePost = @("router.post", ".post(")'
    '    RouteGet = @("router.get", ".get(")'
    '    RoutePut = @("router.put", ".put(")'
    '    RouteDelete = @("router.delete", ".delete(")'
    '}'
    ''
    'function Test-ContainsAny {'
    '    param([string]$Text, [string[]]$Needles)'
    '    foreach ($n in $Needles) {'
    '        if ($Text -match [regex]::Escape($n)) {'
    '            return $true'
    '        }'
    '    }'
    '    return $false'
    '}'
    ''
    '$routeEvidence = New-Object System.Collections.Generic.List[object]'
    '$routePatterns = @('
    '    "matter_type","matterType","case_type","caseType",'
    '    "title","client_id","status","description",'
    '    "INSERT","UPDATE","SELECT","DELETE","CREATE TABLE",'
    '    "router.get","router.post","router.put","router.patch","router.delete",'
    '    "req.body","db.run","db.all","db.get"'
    ')'
    ''
    'foreach ($pattern in $routePatterns) {'
    '    foreach ($filePath in @($BackendCasesRoute, $ApiJs, $CasesJsx)) {'
    '        if (-not (Test-Path -LiteralPath $filePath)) { continue }'
    ''
    '        $matches = Select-String -LiteralPath $filePath -Pattern $pattern -SimpleMatch -CaseSensitive:$false -ErrorAction SilentlyContinue'
    '        foreach ($match in $matches) {'
    '            $routeEvidence.Add([pscustomobject]@{'
    '                FileName = Split-Path $filePath -Leaf'
    '                RelativePath = Get-RelativePathSafe -BasePath $ProjectRoot -FullPath $filePath'
    '                Pattern = $pattern'
    '                LineNumber = $match.LineNumber'
    '                LineText = ($match.Line.Trim() -replace "\s+", " ")'
    '            })'
    '        }'
    '    }'
    '}'
    '$routeEvidence | Export-Csv -NoTypeInformation -Encoding UTF8 -LiteralPath $RouteEvidencePath'
    'Add-Log ("Backend/API/frontend route evidence created: {0}" -f $RouteEvidencePath)'
    ''
    '$packageEvidence = New-Object System.Collections.Generic.List[object]'
    ''
    'foreach ($pkgPath in @($BackendPackage, $FrontendPackage)) {'
    '    if (-not (Test-Path -LiteralPath $pkgPath)) { continue }'
    '    try {'
    '        $pkg = Get-Content -LiteralPath $pkgPath -Raw | ConvertFrom-Json'
    '        foreach ($sectionName in @("dependencies","devDependencies")) {'
    '            $section = $pkg.$sectionName'
    '            if ($section -eq $null) { continue }'
    ''
    '            $section.PSObject.Properties | ForEach-Object {'
    '                $name = $_.Name'
    '                $version = [string]$_.Value'
    '                $isDbRelated = $false'
    '                if ($name -match "sqlite|better-sqlite3|knex|sequelize|typeorm|prisma|drizzle|mysql|postgres|pg") {'
    '                    $isDbRelated = $true'
    '                }'
    ''
    '                $packageEvidence.Add([pscustomobject]@{'
    '                    PackageFile = Get-RelativePathSafe -BasePath $ProjectRoot -FullPath $pkgPath'
    '                    Section = $sectionName'
    '                    Dependency = $name'
    '                    Version = $version'
    '                    IsDatabaseRelated = $isDbRelated'
    '                })'
    '            }'
    '        }'
    '    } catch {'
    '        $packageEvidence.Add([pscustomobject]@{'
    '            PackageFile = Get-RelativePathSafe -BasePath $ProjectRoot -FullPath $pkgPath'
    '            Section = "ERROR"'
    '            Dependency = "PACKAGE_PARSE_ERROR"'
    '            Version = $_.Exception.Message'
    '            IsDatabaseRelated = $false'
    '        })'
    '    }'
    '}'
    ''
    '$packageEvidence | Export-Csv -NoTypeInformation -Encoding UTF8 -LiteralPath $PackageEvidencePath'
    'Add-Log ("Package dependency evidence created: {0}" -f $PackageEvidencePath)'
    ''
    '$dbReview = New-Object System.Collections.Generic.List[object]'
    ''
    'if ($Latest12ESqliteCandidates) {'
    '    $candidates = Import-Csv -LiteralPath $Latest12ESqliteCandidates.FullName'
    '    foreach ($candidate in $candidates) {'
    '        $relative = [string]$candidate.RelativePath'
    '        $full = [string]$candidate.FullPath'
    '        $score = 0'
    '        $reason = New-Object System.Collections.Generic.List[string]'
    ''
    '        if ($relative -match "backend") { $score += 5; $reason.Add("backend path") }'
    '        if ($relative -match "data|db|database|sqlite") { $score += 4; $reason.Add("database-like path/name") }'
    '        if ($relative -match "backup|snapshot|copy|old|archive") { $score -= 5; $reason.Add("backup/archive-like path") }'
    '        if ([int64]$candidate.SizeBytes -gt 0) { $score += 1; $reason.Add("non-empty") }'
    ''
    '        $classification = "REVIEW"'
    '        if ($score -ge 7) { $classification = "LIKELY_ACTIVE_CANDIDATE" }'
    '        elseif ($score -le 0) { $classification = "LOW_PRIORITY_OR_BACKUP" }'
    ''
    '        $dbReview.Add([pscustomobject]@{'
    '            FileName = $candidate.FileName'
    '            RelativePath = $relative'
    '            FullPath = $full'
    '            SizeBytes = $candidate.SizeBytes'
    '            LastWriteTime = $candidate.LastWriteTime'
    '            Score = $score'
    '            Classification = $classification'
    '            Reason = ($reason -join "; ")'
    '        })'
    '    }'
    '} else {'
    '    $dbReview.Add([pscustomobject]@{'
    '        FileName = "NO_12E_SQLITE_CANDIDATE_CSV"'
    '        RelativePath = ""'
    '        FullPath = ""'
    '        SizeBytes = 0'
    '        LastWriteTime = ""'
    '        Score = 0'
    '        Classification = "MISSING_INPUT"'
    '        Reason = "Could not find latest Phase 12.0E SQLite candidate CSV"'
    '    })'
    '}'
    ''
    '$dbReview | Sort-Object Score -Descending | Export-Csv -NoTypeInformation -Encoding UTF8 -LiteralPath $DbCandidateReviewPath'
    'Add-Log ("SQLite candidate planning review created: {0}" -f $DbCandidateReviewPath)'
    ''
    '$matrix = New-Object System.Collections.Generic.List[object]'
    ''
    'Add-MatrixRow $matrix "Database" "Matter Type column exists in active matters/cases table" "Phase 12.0E database signal false or unavailable because sqlite3 was not available" "Identify active SQLite file, inspect schema, then prepare controlled migration only if missing" "UI could submit unsupported data that is ignored or crashes" "REQUIRED_BEFORE_PATCH"'
    'Add-MatrixRow $matrix "Backend Route" "cases.js accepts matter_type in create/update body" ("Matter type in backend route: {0}" -f (Test-ContainsAny $routeText $terms.MatterType)) "Plan request-body extraction, validation, SQL insert/update/select changes" "Matter Type may not be saved or returned" "REQUIRED_BEFORE_PATCH"'
    'Add-MatrixRow $matrix "Frontend API" "api.js can send and receive matter_type without dropping field" ("Matter type in api.js: {0}" -f (Test-ContainsAny $apiText $terms.MatterType)) "Plan API payload passthrough after backend support is confirmed" "Frontend may display field but backend never receives it" "REQUIRED_BEFORE_PATCH"'
    'Add-MatrixRow $matrix "Frontend UI" "Cases.jsx exposes Matter Type dropdown only after support exists" ("Matter type in Cases.jsx: {0}" -f (Test-ContainsAny $casesText $terms.MatterType)) "Defer UI dropdown until backend/database support is certified" "False UI field creates fake functionality" "DEFER"'
    'Add-MatrixRow $matrix "Validation" "Allowed matter type values are fixed and documented" "Not yet implemented" "Use approved list: Litigation, Advisory, Contract, Conveyancing, Debt Recovery, Employment, Family, Criminal, Corporate, Other" "Inconsistent reporting categories" "REQUIRED_BEFORE_PATCH"'
    'Add-MatrixRow $matrix "Rollback" "Database and backend rollback plan exists" "Not yet prepared for Matter Type" "Prepare migration rollback before any patch" "Hard to undo schema changes safely" "REQUIRED_BEFORE_PATCH"'
    'Add-MatrixRow $matrix "Testing" "Create/list/edit flow confirms Matter Type persists" "Not yet testable" "Prepare tests after backend/database plan" "Field may look correct but not persist" "REQUIRED_BEFORE_PATCH"'
    ''
    '$matrix | Export-Csv -NoTypeInformation -Encoding UTF8 -LiteralPath $PlanningMatrixPath'
    'Add-Log ("Planning matrix created: {0}" -f $PlanningMatrixPath)'
    ''
    '$FrontendSignal = Test-ContainsAny $casesText $terms.MatterType'
    '$ApiSignal = Test-ContainsAny $apiText $terms.MatterType'
    '$BackendSignal = Test-ContainsAny $routeText $terms.MatterType'
    '$DbSignal = $false'
    'if ($Summary12E -ne $null) {'
    '    $DbSignal = [bool]$Summary12E.DatabaseMatterTypeMention'
    '}'
    ''
    '$NextRecommendedPhase = "PHASE 12.0G - ACTIVE DATABASE IDENTIFICATION AND SCHEMA INSPECTION"'
    '$PlanningDecision = "PATCH_NOT_APPROVED_BACKEND_DATABASE_PLANNING_REQUIRED"'
    ''
    'if ($Summary12E -ne $null -and $Summary12E.SqliteSchemaStatus -eq "SQLITE3_COMMAND_NOT_AVAILABLE") {'
    '    $NextRecommendedPhase = "PHASE 12.0G - SQLITE SCHEMA ACCESS AND ACTIVE DATABASE IDENTIFICATION"'
    '}'
    ''
    '$summary = [pscustomobject]@{'
    '    GeneratedAt = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")'
    '    Phase = "PHASE 12.0F"'
    '    Mode = "READ_ONLY_BACKEND_DATABASE_PLANNING"'
    '    ProjectRoot = $ProjectRoot'
    '    PhaseRoot = $PhaseRoot'
    '    Phase12ESummary = if ($Latest12ESummary) { $Latest12ESummary.FullName } else { "" }'
    '    Phase12EFinalReport = if ($Latest12EFinalReport) { $Latest12EFinalReport.FullName } else { "" }'
    '    FrontendMatterTypeSignal = $FrontendSignal'
    '    ApiMatterTypeSignal = $ApiSignal'
    '    BackendMatterTypeSignal = $BackendSignal'
    '    DatabaseMatterTypeSignal = $DbSignal'
    '    Sqlite3AvailableInPhase12E = if ($Summary12E -ne $null) { $Summary12E.SqliteSchemaStatus -ne "SQLITE3_COMMAND_NOT_AVAILABLE" } else { $false }'
    '    SqliteCandidatesFoundInPhase12E = if ($Summary12E -ne $null) { $Summary12E.SqliteCandidatesFound } else { 0 }'
    '    PlanningDecision = $PlanningDecision'
    '    NextRecommendedPhase = $NextRecommendedPhase'
    '    PlanningMatrix = $PlanningMatrixPath'
    '    RouteEvidence = $RouteEvidencePath'
    '    PackageEvidence = $PackageEvidencePath'
    '    DbCandidateReview = $DbCandidateReviewPath'
    '}'
    ''
    '$summary | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $JsonSummaryPath -Encoding UTF8'
    ''
    '$lines = New-Object System.Collections.Generic.List[string]'
    '$lines.Add("# PHASE 12.0F READ-ONLY BACKEND / DATABASE PLANNING REPORT")'
    '$lines.Add("")'
    '$lines.Add(("Generated: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss")))'
    '$lines.Add("")'
    '$lines.Add("## Executive Decision")'
    '$lines.Add("")'
    '$lines.Add("Matter Type UI patch remains NOT APPROVED.")'
    '$lines.Add("")'
    '$lines.Add("Phase 12.0E completed successfully as discovery, but found no confirmed Matter Type support in frontend, API, backend, or database evidence.")'
    '$lines.Add("The next action is backend/database planning and active database identification, not UI work.")'
    '$lines.Add("")'
    '$lines.Add("## Phase 12.0E Inputs")'
    '$lines.Add("")'
    '$lines.Add(("- Latest 12.0E summary: {0}" -f $(if ($Latest12ESummary) { $Latest12ESummary.FullName } else { "NOT FOUND" })))'
    '$lines.Add(("- Latest 12.0E final report: {0}" -f $(if ($Latest12EFinalReport) { $Latest12EFinalReport.FullName } else { "NOT FOUND" })))'
    'if ($Summary12E -ne $null) {'
    '    $lines.Add(("- 12.0E preliminary recommendation: {0}" -f $Summary12E.PreliminaryRecommendation))'
    '    $lines.Add(("- 12.0E SQLite schema status: {0}" -f $Summary12E.SqliteSchemaStatus))'
    '    $lines.Add(("- 12.0E SQLite candidates found: {0}" -f $Summary12E.SqliteCandidatesFound))'
    '}'
    '$lines.Add("")'
    '$lines.Add("## Current Signals")'
    '$lines.Add("")'
    '$lines.Add(("- Frontend Matter Type signal: {0}" -f $FrontendSignal))'
    '$lines.Add(("- API Matter Type signal: {0}" -f $ApiSignal))'
    '$lines.Add(("- Backend Matter Type signal: {0}" -f $BackendSignal))'
    '$lines.Add(("- Database Matter Type signal from 12.0E: {0}" -f $DbSignal))'
    '$lines.Add("")'
    '$lines.Add("## Created Evidence")'
    '$lines.Add("")'
    '$lines.Add(("- Planning matrix: {0}" -f $PlanningMatrixPath))'
    '$lines.Add(("- Route/API/frontend evidence: {0}" -f $RouteEvidencePath))'
    '$lines.Add(("- Package DB dependency evidence: {0}" -f $PackageEvidencePath))'
    '$lines.Add(("- SQLite candidate review: {0}" -f $DbCandidateReviewPath))'
    '$lines.Add(("- JSON summary: {0}" -f $JsonSummaryPath))'
    '$lines.Add(("- Log: {0}" -f $LogPath))'
    '$lines.Add("")'
    '$lines.Add("## Next Recommended Phase")'
    '$lines.Add("")'
    '$lines.Add($NextRecommendedPhase)'
    '$lines.Add("")'
    '$lines.Add("## Required Future Work Before Any Matter Type Patch")'
    '$lines.Add("")'
    '$lines.Add("1. Identify the active SQLite database file, not merely every candidate database file.")'
    '$lines.Add("2. Inspect the active schema through an available safe method.")'
    '$lines.Add("3. Confirm the actual matters/cases table name.")'
    '$lines.Add("4. Prepare a migration plan for matter_type if missing.")'
    '$lines.Add("5. Prepare backend route changes to accept, validate, save, and return matter_type.")'
    '$lines.Add("6. Prepare frontend API changes only after backend support is confirmed.")'
    '$lines.Add("7. Prepare UI dropdown only after database and backend support are certified.")'
    '$lines.Add("8. Prepare rollback and test cases before implementation.")'
    '$lines.Add("")'
    '$lines.Add("## Safety Confirmation")'
    '$lines.Add("")'
    '$lines.Add("- Frontend source modification: NO")'
    '$lines.Add("- Backend source modification: NO")'
    '$lines.Add("- Database modification: NO")'
    '$lines.Add("- Phase 11 status: LOCKED")'
    '$lines.Add("")'
    '$lines.Add("END OF PHASE 12.0F PLANNING REPORT")'
    '$lines.Add("")'
    ''
    'Set-Content -LiteralPath $PlanningReportPath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8'
    ''
    'Add-Log ("Planning report created: {0}" -f $PlanningReportPath)'
    'Add-Log "Phase 12.0F read-only backend/database planning completed successfully."'
    ''
    'Write-Host ""'
    'Write-Host "============================================================" -ForegroundColor Green'
    'Write-Host "PHASE 12.0F READ-ONLY PLANNING COMPLETED" -ForegroundColor Green'
    'Write-Host "============================================================" -ForegroundColor Green'
    'Write-Host ""'
    'Write-Host "Planning report:" -ForegroundColor Cyan'
    'Write-Host $PlanningReportPath'
    'Write-Host ""'
    'Write-Host "JSON summary:" -ForegroundColor Cyan'
    'Write-Host $JsonSummaryPath'
    'Write-Host ""'
    ''
    'exit 0'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "06_SCRIPTS\Create-PHASE12.0F-Final-Planning-Certification-Report.ps1"
Write-Lines -Path $TargetPath -Lines @(
    '# ============================================================'
    '# PHASE 12.0F - FINAL PLANNING CERTIFICATION REPORT'
    '# Safety:'
    '#   Certifies planning only. Does not approve patching.'
    '# ============================================================'
    ''
    '$ErrorActionPreference = "Stop"'
    ''
    '$ControlRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software_LEOS_CONTROL"'
    '$PhaseRoot = Join-Path $ControlRoot "07_DISCOVERY\PHASE12.0F-MATTER-TYPE-BACKEND-DATABASE-PLANNING"'
    ''
    '$ReportsRoot = Join-Path $PhaseRoot "07_REPORTS"'
    '$EvidenceRoot = Join-Path $PhaseRoot "08_EVIDENCE"'
    ''
    'New-Item -ItemType Directory -Force -Path $ReportsRoot | Out-Null'
    ''
    '$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"'
    '$FinalReport = Join-Path $ReportsRoot "PHASE12.0F-FINAL-PLANNING-CERTIFICATION-REPORT-$Timestamp.md"'
    ''
    '$LatestSummary = Get-ChildItem -LiteralPath $EvidenceRoot -Filter "PHASE12.0F-PLANNING-SUMMARY-*.json" -File -ErrorAction SilentlyContinue |'
    '    Sort-Object LastWriteTime -Descending |'
    '    Select-Object -First 1'
    ''
    '$LatestPlanningReport = Get-ChildItem -LiteralPath $ReportsRoot -Filter "PHASE12.0F-READONLY-BACKEND-DATABASE-PLANNING-REPORT-*.md" -File -ErrorAction SilentlyContinue |'
    '    Sort-Object LastWriteTime -Descending |'
    '    Select-Object -First 1'
    ''
    '$summary = $null'
    'if ($LatestSummary) {'
    '    try {'
    '        $summary = Get-Content -LiteralPath $LatestSummary.FullName -Raw | ConvertFrom-Json'
    '    } catch {'
    '        $summary = $null'
    '    }'
    '}'
    ''
    '$lines = New-Object System.Collections.Generic.List[string]'
    ''
    '$lines.Add("# PHASE 12.0F FINAL PLANNING CERTIFICATION REPORT")'
    '$lines.Add("")'
    '$lines.Add(("Generated: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss")))'
    '$lines.Add("")'
    '$lines.Add("## Certification Scope")'
    '$lines.Add("")'
    '$lines.Add("This certifies read-only backend/database planning after Phase 12.0E.")'
    '$lines.Add("This does not approve source-code patching, database migration, UI exposure, or Phase 11.")'
    '$lines.Add("")'
    '$lines.Add("## Latest Planning Inputs")'
    '$lines.Add("")'
    '$lines.Add(("- Latest planning report: {0}" -f $(if ($LatestPlanningReport) { $LatestPlanningReport.FullName } else { "NOT FOUND" })))'
    '$lines.Add(("- Latest planning summary: {0}" -f $(if ($LatestSummary) { $LatestSummary.FullName } else { "NOT FOUND" })))'
    '$lines.Add("")'
    ''
    'if ($summary -eq $null) {'
    '    $lines.Add("## Certification Decision")'
    '    $lines.Add("")'
    '    $lines.Add("STATUS: FAIL")'
    '    $lines.Add("")'
    '    $lines.Add("Reason: No valid planning summary was found.")'
    '} else {'
    '    $lines.Add("## Planning Summary")'
    '    $lines.Add("")'
    '    $lines.Add(("- Frontend Matter Type signal: {0}" -f $summary.FrontendMatterTypeSignal))'
    '    $lines.Add(("- API Matter Type signal: {0}" -f $summary.ApiMatterTypeSignal))'
    '    $lines.Add(("- Backend Matter Type signal: {0}" -f $summary.BackendMatterTypeSignal))'
    '    $lines.Add(("- Database Matter Type signal: {0}" -f $summary.DatabaseMatterTypeSignal))'
    '    $lines.Add(("- Planning decision: {0}" -f $summary.PlanningDecision))'
    '    $lines.Add(("- Next recommended phase: {0}" -f $summary.NextRecommendedPhase))'
    '    $lines.Add("")'
    '    $lines.Add("## Certification Decision")'
    '    $lines.Add("")'
    '    $lines.Add("STATUS: PLANNING PASS / PATCH NOT APPROVED")'
    '    $lines.Add("")'
    '    $lines.Add("Reason: Backend/database planning completed, but Matter Type support is still not certified for implementation.")'
    '    $lines.Add("Next action: Execute the next read-only phase for active database identification and schema inspection.")'
    '}'
    ''
    '$lines.Add("")'
    '$lines.Add("## Safety Confirmation")'
    '$lines.Add("")'
    '$lines.Add("- Frontend source modification: NO")'
    '$lines.Add("- Backend source modification: NO")'
    '$lines.Add("- Database modification: NO")'
    '$lines.Add("- Matter Type UI patch approved: NO")'
    '$lines.Add("- Phase 11 status: LOCKED")'
    '$lines.Add("")'
    '$lines.Add("END OF PHASE 12.0F FINAL PLANNING CERTIFICATION REPORT")'
    '$lines.Add("")'
    ''
    'Set-Content -LiteralPath $FinalReport -Value ($lines -join [Environment]::NewLine) -Encoding UTF8'
    ''
    'Write-Host ""'
    'Write-Host "Final Phase 12.0F planning certification report created:" -ForegroundColor Green'
    'Write-Host $FinalReport'
    'Write-Host ""'
    ''
    'exit 0'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "06_SCRIPTS\Run-PHASE12.0F-All-ReadOnly.ps1"
Write-Lines -Path $TargetPath -Lines @(
    '# ============================================================'
    '# PHASE 12.0F - RUN ALL READ-ONLY PLANNING'
    '# Runs planning first, then final certification only if planning succeeds.'
    '# ============================================================'
    ''
    '$ErrorActionPreference = "Stop"'
    ''
    '$ControlRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software_LEOS_CONTROL"'
    '$PhaseRoot = Join-Path $ControlRoot "07_DISCOVERY\PHASE12.0F-MATTER-TYPE-BACKEND-DATABASE-PLANNING"'
    '$ScriptsRoot = Join-Path $PhaseRoot "06_SCRIPTS"'
    ''
    '$PlanningScript = Join-Path $ScriptsRoot "Run-PHASE12.0F-ReadOnly-Planning.ps1"'
    '$FinalScript = Join-Path $ScriptsRoot "Create-PHASE12.0F-Final-Planning-Certification-Report.ps1"'
    ''
    'function Test-PowerShellParse {'
    '    param([string]$Path)'
    ''
    '    $parseErrors = $null'
    '    $tokens = $null'
    '    $null = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$parseErrors)'
    ''
    '    if ($parseErrors -and $parseErrors.Count -gt 0) {'
    '        Write-Host ""'
    '        Write-Host ("PARSER ERROR in {0}" -f $Path) -ForegroundColor Red'
    '        foreach ($err in $parseErrors) {'
    '            Write-Host ("- {0}" -f $err.Message) -ForegroundColor Red'
    '        }'
    '        return $false'
    '    }'
    ''
    '    return $true'
    '}'
    ''
    'Write-Host ""'
    'Write-Host "============================================================" -ForegroundColor Cyan'
    'Write-Host "PHASE 12.0F - RUN ALL READ-ONLY PLANNING" -ForegroundColor Cyan'
    'Write-Host "============================================================" -ForegroundColor Cyan'
    'Write-Host ""'
    ''
    'if (-not (Test-Path -LiteralPath $PlanningScript)) {'
    '    Write-Host "Planning script missing." -ForegroundColor Red'
    '    exit 1'
    '}'
    ''
    'if (-not (Test-Path -LiteralPath $FinalScript)) {'
    '    Write-Host "Final planning certification script missing." -ForegroundColor Red'
    '    exit 1'
    '}'
    ''
    'if (-not (Test-PowerShellParse -Path $PlanningScript)) {'
    '    Write-Host "Planning script failed parser validation. Stopping." -ForegroundColor Red'
    '    exit 1'
    '}'
    ''
    'if (-not (Test-PowerShellParse -Path $FinalScript)) {'
    '    Write-Host "Final planning script failed parser validation. Stopping." -ForegroundColor Red'
    '    exit 1'
    '}'
    ''
    'Write-Host "Running Phase 12.0F read-only backend/database planning..." -ForegroundColor Yellow'
    '& powershell -ExecutionPolicy Bypass -NoProfile -File $PlanningScript'
    '$planningExit = $LASTEXITCODE'
    ''
    'if ($planningExit -ne 0) {'
    '    Write-Host ""'
    '    Write-Host ("Planning failed with exit code {0}. Final planning certification will NOT be created." -f $planningExit) -ForegroundColor Red'
    '    exit $planningExit'
    '}'
    ''
    'Write-Host ""'
    'Write-Host "Creating Phase 12.0F final planning certification report..." -ForegroundColor Yellow'
    '& powershell -ExecutionPolicy Bypass -NoProfile -File $FinalScript'
    '$certExit = $LASTEXITCODE'
    ''
    'if ($certExit -ne 0) {'
    '    Write-Host ""'
    '    Write-Host ("Final planning certification failed with exit code {0}." -f $certExit) -ForegroundColor Red'
    '    exit $certExit'
    '}'
    ''
    'Write-Host ""'
    'Write-Host "============================================================" -ForegroundColor Green'
    'Write-Host "PHASE 12.0F ALL READ-ONLY PLANNING COMPLETED SUCCESSFULLY" -ForegroundColor Green'
    'Write-Host "============================================================" -ForegroundColor Green'
    'Write-Host ""'
    ''
    'exit 0'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$TargetPath = Join-Path $PhaseRoot "06_SCRIPTS\Start-PHASE12.0F-Live-Monitor.ps1"
Write-Lines -Path $TargetPath -Lines @(
    '# ============================================================'
    '# PHASE 12.0F - LIVE PLANNING MONITOR'
    '# Purpose:'
    '#   Monitor Phase 12.0F report/evidence generation and local ports.'
    '# Safety:'
    '#   Read-only monitor.'
    '# ============================================================'
    ''
    'param('
    '    [int]$IntervalSeconds = 10'
    ')'
    ''
    '$ErrorActionPreference = "Stop"'
    ''
    '$ControlRoot = "C:\Users\jep_edmundrulz\litigation-360-workspace\litigation-360-software_LEOS_CONTROL"'
    '$PhaseRoot = Join-Path $ControlRoot "07_DISCOVERY\PHASE12.0F-MATTER-TYPE-BACKEND-DATABASE-PLANNING"'
    '$ReportsRoot = Join-Path $PhaseRoot "07_REPORTS"'
    '$EvidenceRoot = Join-Path $PhaseRoot "08_EVIDENCE"'
    '$MonitorRoot = Join-Path $PhaseRoot "10_LIVE_MONITORING"'
    ''
    'New-Item -ItemType Directory -Force -Path $MonitorRoot | Out-Null'
    ''
    '$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"'
    '$CsvPath = Join-Path $MonitorRoot "PHASE12.0F-live-monitor-$Timestamp.csv"'
    '$MdPath = Join-Path $MonitorRoot "PHASE12.0F-LIVE-STATUS.md"'
    ''
    '"Timestamp,ReportsCount,EvidenceCount,Port5000,Port5100,Port5173,LatestReport,LatestEvidence" | Set-Content -LiteralPath $CsvPath -Encoding UTF8'
    ''
    'Write-Host "PHASE 12.0F live monitor started. Stop with CTRL+C." -ForegroundColor Green'
    'Write-Host ("CSV: {0}" -f $CsvPath)'
    'Write-Host ("Live MD: {0}" -f $MdPath)'
    ''
    'while ($true) {'
    '    $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"'
    ''
    '    $reports = Get-ChildItem -LiteralPath $ReportsRoot -File -ErrorAction SilentlyContinue'
    '    $evidence = Get-ChildItem -LiteralPath $EvidenceRoot -File -ErrorAction SilentlyContinue'
    ''
    '    $latestReport = $reports | Sort-Object LastWriteTime -Descending | Select-Object -First 1'
    '    $latestEvidence = $evidence | Sort-Object LastWriteTime -Descending | Select-Object -First 1'
    ''
    '    $ports = @(5000, 5100, 5173)'
    '    $portStatus = @{}'
    ''
    '    foreach ($p in $ports) {'
    '        $found = $false'
    '        try {'
    '            $conn = Get-NetTCPConnection -LocalPort $p -State Listen -ErrorAction SilentlyContinue'
    '            if ($conn) { $found = $true }'
    '        } catch {'
    '            $found = $false'
    '        }'
    '        $portStatus[$p] = $found'
    '    }'
    ''
    '    $latestReportPath = ""'
    '    if ($latestReport) { $latestReportPath = $latestReport.FullName }'
    ''
    '    $latestEvidencePath = ""'
    '    if ($latestEvidence) { $latestEvidencePath = $latestEvidence.FullName }'
    ''
    '    $csvLine = ''"{0}",{1},{2},{3},{4},{5},"{6}","{7}"'' -f `'
    '        $now,'
    '        ($reports.Count),'
    '        ($evidence.Count),'
    '        ($portStatus[5000]),'
    '        ($portStatus[5100]),'
    '        ($portStatus[5173]),'
    '        ($latestReportPath -replace ''"'',''""''),'
    '        ($latestEvidencePath -replace ''"'',''""'')'
    ''
    '    Add-Content -LiteralPath $CsvPath -Value $csvLine -Encoding UTF8'
    ''
    '    $md = New-Object System.Collections.Generic.List[string]'
    '    $md.Add("# PHASE 12.0F LIVE STATUS")'
    '    $md.Add("")'
    '    $md.Add(("Updated: {0}" -f $now))'
    '    $md.Add("")'
    '    $md.Add("## Counts")'
    '    $md.Add("")'
    '    $md.Add(("- Reports: {0}" -f $reports.Count))'
    '    $md.Add(("- Evidence files: {0}" -f $evidence.Count))'
    '    $md.Add("")'
    '    $md.Add("## Ports")'
    '    $md.Add("")'
    '    foreach ($p in $ports) {'
    '        $md.Add(("- Port {0}: {1}" -f $p, $portStatus[$p]))'
    '    }'
    '    $md.Add("")'
    '    $md.Add("## Latest Files")'
    '    $md.Add("")'
    '    $md.Add(("- Latest report: {0}" -f $latestReportPath))'
    '    $md.Add(("- Latest evidence: {0}" -f $latestEvidencePath))'
    '    $md.Add("")'
    ''
    '    Set-Content -LiteralPath $MdPath -Value ($md -join [Environment]::NewLine) -Encoding UTF8'
    ''
    '    Start-Sleep -Seconds $IntervalSeconds'
    '}'
)
Write-Host ("Created: {0}" -f $TargetPath) -ForegroundColor Green

$ScriptsToValidate = @(
    (Join-Path $PhaseRoot "06_SCRIPTS\Run-PHASE12.0F-ReadOnly-Planning.ps1"),
    (Join-Path $PhaseRoot "06_SCRIPTS\Create-PHASE12.0F-Final-Planning-Certification-Report.ps1"),
    (Join-Path $PhaseRoot "06_SCRIPTS\Run-PHASE12.0F-All-ReadOnly.ps1"),
    (Join-Path $PhaseRoot "06_SCRIPTS\Start-PHASE12.0F-Live-Monitor.ps1")
)

$ParseFailure = $false

foreach ($script in $ScriptsToValidate) {
    $parseErrors = $null
    $tokens = $null
    $null = [System.Management.Automation.Language.Parser]::ParseFile($script, [ref]$tokens, [ref]$parseErrors)

    if ($parseErrors -and $parseErrors.Count -gt 0) {
        $ParseFailure = $true
        Write-Host ""
        Write-Host ("Parser error in: {0}" -f $script) -ForegroundColor Red
        foreach ($err in $parseErrors) {
            Write-Host ("- {0}" -f $err.Message) -ForegroundColor Red
        }
    }
}

$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$SummaryPath = Join-Path $PhaseRoot "07_REPORTS\PHASE12.0F-PACK-CREATION-SUMMARY-$Timestamp.md"

$SummaryLines = @(
    "# PHASE 12.0F PACK CREATION SUMMARY",
    "",
    ("Generated: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss")),
    "",
    "## Status",
    "",
    $(if ($ParseFailure) { "PACK CREATED WITH SCRIPT PARSER ERRORS" } else { "PACK CREATED SUCCESSFULLY" }),
    "",
    "## Phase Root",
    "",
    $PhaseRoot,
    "",
    "## Next Command",
    "",
    ("powershell -NoExit -ExecutionPolicy Bypass -NoProfile -File `"{0}`"" -f (Join-Path $PhaseRoot "06_SCRIPTS\Run-PHASE12.0F-All-ReadOnly.ps1")),
    "",
    "## Optional Monitor Command",
    "",
    ("powershell -NoExit -ExecutionPolicy Bypass -NoProfile -File `"{0}`" -IntervalSeconds 10" -f (Join-Path $PhaseRoot "06_SCRIPTS\Start-PHASE12.0F-Live-Monitor.ps1")),
    "",
    "## Safety",
    "",
    "- Frontend app source modified: NO",
    "- Backend app source modified: NO",
    "- Database modified: NO",
    "- Control documentation/scripts created: YES"
)

Set-Content -LiteralPath $SummaryPath -Value ($SummaryLines -join [Environment]::NewLine) -Encoding UTF8

Write-Host ""
if ($ParseFailure) {
    Write-Host "============================================================" -ForegroundColor Red
    Write-Host "PHASE 12.0F PACK CREATED BUT PARSER VALIDATION FAILED" -ForegroundColor Red
    Write-Host "============================================================" -ForegroundColor Red
    Write-Host "Open the summary report:" -ForegroundColor Yellow
    Write-Host $SummaryPath
    exit 1
}

Write-Host "============================================================" -ForegroundColor Green
Write-Host "PHASE 12.0F BACKEND / DATABASE PLANNING PACK CREATED SUCCESSFULLY" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Phase Root:" -ForegroundColor Cyan
Write-Host $PhaseRoot
Write-Host ""
Write-Host "Next command:" -ForegroundColor Yellow
Write-Host ("powershell -NoExit -ExecutionPolicy Bypass -NoProfile -File `"{0}`"" -f (Join-Path $PhaseRoot "06_SCRIPTS\Run-PHASE12.0F-All-ReadOnly.ps1"))
Write-Host ""
Write-Host "Optional live monitor command:" -ForegroundColor Yellow
Write-Host ("powershell -NoExit -ExecutionPolicy Bypass -NoProfile -File `"{0}`" -IntervalSeconds 10" -f (Join-Path $PhaseRoot "06_SCRIPTS\Start-PHASE12.0F-Live-Monitor.ps1"))
Write-Host ""
Write-Host "Summary report:" -ForegroundColor Cyan
Write-Host $SummaryPath
Write-Host ""

exit 0