export const menuSections = [
  {
    id: "primary",
    title: "Primary",
    priority: 1,
    items: [
      {
        id: "file",
        label: "File",
        type: "submenu",
        icon: "file",
        keywords: ["open", "save", "export", "import", "recent files"],
        children: [
          {
            id: "file-open",
            label: "Open",
            type: "panel",
            icon: "folder-open",
            keywords: ["browse", "load"],
          },
          {
            id: "file-save",
            label: "Save",
            type: "panel",
            icon: "save",
            keywords: ["store", "commit"],
          },
          {
            id: "file-import",
            label: "Import",
            type: "panel",
            icon: "import",
            keywords: ["upload", "bring in"],
          },
          {
            id: "file-export",
            label: "Export",
            type: "panel",
            icon: "export",
            keywords: ["download", "pdf", "csv", "excel"],
          },
          {
            id: "file-recent",
            label: "Recent Files",
            type: "panel",
            icon: "clock",
            keywords: ["history", "last opened"],
          },
        ],
      },
      {
        id: "settings",
        label: "Settings",
        type: "panel",
        icon: "settings",
        keywords: ["preferences", "customize", "theme", "account"],
      },
    ],
  },
  {
    id: "legal-notices",
    title: "Legal & Notices",
    priority: 2,
    items: [
      {
        id: "legal-notice",
        label: "Disclaimer / Copyright Notice",
        type: "panel",
        icon: "info",
        description: "View copyright, trademark, restrictions, liability, third-party content, and governing-law notice.",
        keywords: ["legal", "copyright", "disclaimer", "trademark", "notice", "liability"],
      },
    ],
  },
  {
    id: "help-info",
    title: "Help & Info",
    priority: 3,
    items: [
      {
        id: "faq",
        label: "FAQ",
        type: "panel",
        icon: "help-circle",
        keywords: ["help", "common issues", "question", "guide"],
      },
      {
        id: "submit-request",
        label: "Submit Query / Request",
        type: "panel",
        icon: "message-square",
        keywords: ["support", "ticket", "bug", "feedback", "screenshot", "crash"],
      },
      {
        id: "about-app",
        label: "About App",
        type: "panel",
        icon: "info",
        keywords: ["version", "license", "credits", "release notes", "updates"],
      },
      {
        id: "about-system",
        label: "About System",
        type: "panel",
        icon: "monitor",
        keywords: ["device", "os", "hardware", "browser", "environment"],
      },
    ],
  },
];
