const EVENT_TYPES = {
  CLIENT_CREATED: "CLIENT_CREATED",
  MATTER_CREATED: "MATTER_CREATED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  TASK_COMPLETED: "TASK_COMPLETED",
  COURT_DATE_ADDED: "COURT_DATE_ADDED",
  DEADLINE_CREATED: "DEADLINE_CREATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  INVOICE_CREATED: "INVOICE_CREATED",
  USER_CREATED: "USER_CREATED",
  ROLE_CHANGED: "ROLE_CHANGED"
};

module.exports = EVENT_TYPES;
