CREATE TABLE clients (id INTEGER PRIMARY KEY AUTOINCREMENT, full_name TEXT NOT NULL, email TEXT, phone TEXT, address TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE staff (id INTEGER PRIMARY KEY AUTOINCREMENT, full_name TEXT NOT NULL, role TEXT NOT NULL, email TEXT UNIQUE, phone TEXT, nric TEXT UNIQUE, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cases (id INTEGER PRIMARY KEY AUTOINCREMENT, case_number TEXT UNIQUE, title TEXT NOT NULL, client_id INTEGER, status TEXT DEFAULT 'Active', description TEXT, opened_date DATE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES clients(id));
CREATE TABLE deadlines (id INTEGER PRIMARY KEY AUTOINCREMENT, case_id INTEGER, title TEXT NOT NULL, deadline_date DATE NOT NULL, reminder_days INTEGER DEFAULT 7, notes TEXT, is_complete INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (case_id) REFERENCES cases(id));

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'legal_assistant_clerk',
  staff_id INTEGER,
  is_active INTEGER NOT NULL DEFAULT 1,
  last_login DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE permissions (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE role_permissions (role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (role_id, permission_id));
CREATE TABLE audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_email TEXT, action TEXT NOT NULL, entity_type TEXT, entity_id TEXT, old_value TEXT, new_value TEXT, ip_address TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE security_events (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT, event_type TEXT, ip_address TEXT, details TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
