module.exports = {
  CLIENT_CREATED: "CLIENT_CREATED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_DELETED: "CLIENT_DELETED",

  MATTER_CREATED: "MATTER_CREATED",
  MATTER_UPDATED: "MATTER_UPDATED",
  MATTER_CLOSED: "MATTER_CLOSED",

  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",

  TASK_CREATED: "TASK_CREATED",
  TASK_COMPLETED: "TASK_COMPLETED",

  DEADLINE_CREATED: "DEADLINE_CREATED",
  DEADLINE_UPDATED: "DEADLINE_UPDATED",

  COURT_DATE_ADDED: "COURT_DATE_ADDED",
  COURT_DATE_UPDATED: "COURT_DATE_UPDATED",

  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",

  SECURITY_ALERT: "SECURITY_ALERT",
  SYSTEM_ERROR: "SYSTEM_ERROR",

  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE"
};
